# Generated by Django 3.2.3 on 2021-07-15 02:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_auto_20210708_0047"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="type",
            new_name="event_type",
        ),
        migrations.AlterField(
            model_name="attentionschedule",
            name="day",
            field=models.IntegerField(
                choices=[
                    (0, "Domingo"),
                    (1, "Lunes"),
                    (2, "Martes"),
                    (3, "Miercoles"),
                    (4, "Jueves"),
                    (5, "Viernes"),
                    (6, "Sabado"),
                ]
            ),
        ),
    ]
