# Generated by Django 3.2.3 on 2021-08-30 22:20
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_auto_20210715_0226"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="goal",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.URLField(null=True),
        ),
    ]
