# Generated by Django 3.2.3 on 2021-08-30 22:24
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_auto_20210830_2220"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registred_at",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
