# Generated by Django 3.2.3 on 2021-08-30 23:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_auto_20210830_2224"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="registred_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
