# Generated by Django 3.2.3 on 2021-10-30 16:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_event_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cancelled_at",
            field=models.DateTimeField(null=True),
        ),
    ]
