# Generated by Django 3.2.3 on 2024-08-19 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_event_cancelled_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("done", models.BooleanField()),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="items",
                        to="app.event",
                    ),
                ),
            ],
        ),
    ]
