# Generated by Django 3.2.3 on 2024-08-20 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_eventitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventitem",
            old_name="event_id",
            new_name="event",
        ),
    ]
