# Generated by Django 3.2.3 on 2024-08-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_rename_event_id_eventitem_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventitem",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
