# Generated by Django 3.2.3 on 2024-08-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
