# Generated by Django 3.2.3 on 2024-09-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="shared",
            field=models.IntegerField(default=0),
        ),
    ]
